print('Dissecando uma Variável ')
num = input('Digite algo: ')
print('O tipo printivo desse valor é ', type(num))
print('Só tem espaços? ', num.isspace())
print('É número? ', num.isnumeric())
print('É alfabético? ', num.isalpha())
print('É alfanumérico?', num.isalnum())
print('Está em maiusculas? ', num.isupper())
print('Está em minúculas? ', num.islower())
print('Está capitalizada? ', num.istitle())
